class Answer < ApplicationRecord
  # generated by doing: rails g model answer body:text question:references

  # BY deafult, 'belongs_to' will create a validation such as "validates :question_id, presence: true"
  # It can be disabled by passing the option: "optional: true" to the belongs_to method
  #e.g. belongs_to :question, optional: true

  # In an association betweeen two models, the model that has the 'belongs_to' is always the one whose table contains the foreign_key (i.e. question_id)

  belongs_to :question
  belongs_to :user

  # The following instance methods are added to the
  # Answer model with the line belongs_to :question
  # They simplify interaction with the associated question
  # .question - getter method
  # .question=(associate) - setter method; we are able to re-set the question_id
  # .build_question(attributes = {})
  # .create_question(attributes = {})
  # .create_question!(attributes = {})
  # .reload_question

  validates :body, presence: true
end
